version: '3.7'
services:
  tests:
    build:
      context: .
      dockerfile: './Simple.Redis.Tests/dockerfile'
    depends_on: 
      - 'redis_service'
  redis_service:
    image: 'redis'
    restart: always
    ports:
      - '6379:6379'